name: waterbuddy_customer_app
description: WaterBuddy customer mobile app.
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_messaging: ^15.0.1
  url_launcher: ^6.3.0
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  razorpay_flutter: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/google_logo.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
