export const collections = {
  users: "users",
  sellers: "sellers",
  drivers: "drivers",
  admins: "admins",
  orders: "orders",
  orderOffers: "order_offers",
  notifications: "notifications",
  dispatchLogs: "dispatch_logs",
  systemSettings: "system_settings",
  sellerLocations: "seller_locations",
  driverLocations: "driver_locations",
  tracking: "tracking",
  complaints: "complaints",
  // Phase 5 additions
  paymentEvents: "payment_events",
  ratings: "ratings",
  ratingAggregates: "rating_aggregates",
  systemMetrics: "system_metrics",
} as const;
