import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./modules/**/*.{js,ts,jsx,tsx}",
    "./hooks/**/*.{js,ts,jsx,tsx}",
    "./services/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#f7f9fb",
          100: "#eceef0",
          300: "#757682",
          400: "#444651",
          500: "#00236f",
          600: "#1e3a8a",
          700: "#264191",
        },
        cream: "#f2f4f6",
        lilac: "#57dffe",
        surface: "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-dim": "#d8dadc",
        "surface-variant": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#444651",
        outline: "#757682",
        "outline-variant": "#c5c5d3",
        primary: "#00236f",
        "primary-container": "#1e3a8a",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#90a8ff",
        "on-primary-fixed": "#00164e",
        "on-primary-fixed-variant": "#264191",
        secondary: "#00687a",
        "secondary-container": "#57dffe",
        "secondary-fixed": "#acedff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#006172",
        "on-secondary-fixed": "#001f26",
        "on-secondary-fixed-variant": "#004e5c",
        tertiary: "#00312b",
        "tertiary-container": "#004941",
        "tertiary-fixed": "#71f8e4",
        "tertiary-fixed-dim": "#4fdbc8",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#27c0ae",
        "on-tertiary-fixed": "#00201c",
        "on-tertiary-fixed-variant": "#005048",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        background: "#f7f9fb",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#b6c4ff",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
