import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./modules/**/*.{js,ts,jsx,tsx}",
    "./hooks/**/*.{js,ts,jsx,tsx}",
    "./services/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#f7f9fb",
          100: "#eceef0",
          300: "#757682",
          400: "#444651",
          500: "#14B8A6",
          600: "#0F766E",
          700: "#042F2E",
        },
        cream: "#0D1117",
        lilac: "#14B8A6",
        surface: "#0D1117",
        "surface-container-low": "#0A0D14",
        "surface-container-lowest": "#050608",
        "surface-container": "#111721",
        "surface-container-high": "#161E2C",
        "surface-container-highest": "#1A2536",
        "surface-dim": "#080A0F",
        "surface-variant": "#1A2536",
        "on-surface": "#F0F3F7",
        "on-surface-variant": "#A0AEC0",
        outline: "#4A5568",
        "outline-variant": "#2D3748",
        primary: "#14B8A6",
        "primary-container": "#0F766E",
        "primary-fixed": "#14B8A6",
        "primary-fixed-dim": "#0F766E",
        "on-primary": "#FFFFFF",
        "on-primary-container": "#CCFBF1",
        "on-primary-fixed": "#FFFFFF",
        "on-primary-fixed-variant": "#CCFBF1",
        secondary: "#0EA5E9",
        "secondary-container": "#0369A1",
        "secondary-fixed": "#0EA5E9",
        "secondary-fixed-dim": "#0369A1",
        "on-secondary": "#FFFFFF",
        "on-secondary-container": "#E0F2FE",
        "on-secondary-fixed": "#FFFFFF",
        "on-secondary-fixed-variant": "#E0F2FE",
        tertiary: "#8B5CF6",
        "tertiary-container": "#5B21B6",
        "tertiary-fixed": "#8B5CF6",
        "tertiary-fixed-dim": "#5B21B6",
        "on-tertiary": "#FFFFFF",
        "on-tertiary-container": "#EDE9FE",
        "on-tertiary-fixed": "#FFFFFF",
        "on-tertiary-fixed-variant": "#EDE9FE",
        error: "#F87171",
        "error-container": "#991B1B",
        "on-error": "#FFFFFF",
        "on-error-container": "#FEF2F2",
        background: "#0D1117",
        "inverse-surface": "#E2E8F0",
        "inverse-on-surface": "#0F172A",
        "inverse-primary": "#14B8A6",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
