import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./modules/**/*.{js,ts,jsx,tsx}",
    "./hooks/**/*.{js,ts,jsx,tsx}",
    "./services/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#eff6ff",
          100: "#dbeafe",
          300: "#7dd3fc",
          400: "#38bdf8",
          500: "#0ea5e9",
          600: "#0284c7",
          700: "#0369a1",
        },
        cream: "#f8fbff",
        lilac: "#0ea5e9",
        surface: "#ffffff",
        "surface-container-low": "#f8fbff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f0f9ff",
        "surface-container-high": "#e0f2fe",
        "surface-container-highest": "#bae6fd",
        "surface-dim": "#e2e8f0",
        "surface-variant": "#dbeafe",
        "on-surface": "#0f172a",
        "on-surface-variant": "#475569",
        outline: "#93c5fd",
        "outline-variant": "#dbeafe",
        primary: "#0ea5e9",
        "primary-container": "#dbeafe",
        "primary-fixed": "#0ea5e9",
        "primary-fixed-dim": "#0284c7",
        "on-primary": "#FFFFFF",
        "on-primary-container": "#075985",
        "on-primary-fixed": "#FFFFFF",
        "on-primary-fixed-variant": "#dbeafe",
        secondary: "#0284c7",
        "secondary-container": "#0369A1",
        "secondary-fixed": "#0ea5e9",
        "secondary-fixed-dim": "#0369A1",
        "on-secondary": "#FFFFFF",
        "on-secondary-container": "#E0F2FE",
        "on-secondary-fixed": "#FFFFFF",
        "on-secondary-fixed-variant": "#E0F2FE",
        tertiary: "#8B5CF6",
        "tertiary-container": "#5B21B6",
        "tertiary-fixed": "#8B5CF6",
        "tertiary-fixed-dim": "#5B21B6",
        "on-tertiary": "#FFFFFF",
        "on-tertiary-container": "#EDE9FE",
        "on-tertiary-fixed": "#FFFFFF",
        "on-tertiary-fixed-variant": "#EDE9FE",
        error: "#F87171",
        "error-container": "#991B1B",
        "on-error": "#FFFFFF",
        "on-error-container": "#FEF2F2",
        background: "#0D1117",
        "inverse-surface": "#E2E8F0",
        "inverse-on-surface": "#0F172A",
        "inverse-primary": "#14B8A6",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
